apiVersion: v1
kind: Secret
metadata:
  name: job-portal-secrets
  namespace: job-portal
type: Opaque
data:
  # Base64 encoded values from .env file
  # To encode: echo -n "your-value" | base64
  
  # MONGO_URI=mongodb://mongodb-service:27017/jobportal (local Kubernetes MongoDB)
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9qb2Jwb3J0YWw=
  
  # SECRET_KEY=azazazazaza
  SECRET_KEY: YXphemF6YXphemF6YQ==
  
  # CLOUD_NAME=dkoapy30w
  CLOUD_NAME: ZGtvYXB5MzB3
  
  # API_KEY=191485719394427
  API_KEY: MTkxNDg1NzE5Mzk0NDI3
  
  # API_SECRET=bUeTFAsVmB1CAJwtpu__ikl8v2M
  API_SECRET: YlVlVEZBc1ZtQjFDQUp3dHB1X19pa2w4djJN
  
  # GOOGLE_CLIENT_ID=990128340658-ldli8m2948al9pu0rmhos95tlo6v0v99.apps.googleusercontent.com
  GOOGLE_CLIENT_ID: OTkwMTI4MzQwNjU4LWxkbGk4bTI5NDhhbDlwdTBybWhvczk1dGxvNnYwdjk5LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  
  # PORT=8000
  PORT: ODAwMA==
